### PR TITLE
Leverage `getNativeConnection()` when checking the transaction state

### LINKED ISSUE #1247: Issues when using DBAL middlewares
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.4.1

#### Summary

With DoctrineBundle 2.6 we enabled the new DBAL logging middleware and I noticed that this breaks migrations on one of my apps.

#### Current behavior

When running migrations on my app I get

```
In Connection.php line 123:
                                  
  [PDOException]                  
  There is no active transaction  
                                  

Exception trace:
  at /var/www/app/symfony/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:123
 PDO->rollBack() at /var/www/app/symfony/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:123
 Doctrine\DBAL\Driver\PDO\Connection->rollBack() at /var/www/app/symfony/vendor/doctrine/dbal/src/Driver/Middleware/AbstractConnectionMiddleware.php:87
 Doctrine\DBAL\Driver\Middleware\AbstractConnectionMiddleware->rollBack() at /var/www/app/symfony/vendor/doctrine/dbal/src/Logging/Connection.php:83
 Doctrine\DBAL\Logging\Connection->rollBack() at /var/www/app/symfony/vendor/doctrine/dbal/src/Connection.php:1419
 Doctrine\DBAL\Connection->rollBack() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/TransactionHelper.php:57
 Doctrine\Migrations\Tools\TransactionHelper::rollbackIfInTransaction() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:257
 Doctrine\Migrations\Version\DbalExecutor->migrationEnd() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:115
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:112
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:76
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:162
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/app/symfony/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php:210
 Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() at /var/www/app/symfony/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/app/symfony/vendor/symfony/console/Application.php:1033
 Symfony\Component\Console\Application->doRunCommand() at /var/www/app/symfony/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/app/symfony/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /var/www/app/symfony/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/app/symfony/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/app/symfony/app/console:35
```

The issue is with the logic inside [`TransactionHelper`](https://github.com/doctrine/migrations/blob/3.4.x/lib/Doctrine/Migrations/Tools/TransactionHelper.php#L63). 
For the `Doctrine\DBAL\Logging\Connection` class this does not work since there is only the method [`getNativeConnection`](https://github.com/doctrine/dbal/blob/3.3.x/src/Driver/Middleware/AbstractConnectionMiddleware.php#L105) to access the underlying connection.

#### How to reproduce

Run migrations using DoctrineBundle 2.6.0 and DBAL 3 using `PDO` (Mysql in my case).

#### Expected behavior

It should handle the decorated connection instance properly.

### PR DESCRIPTION
**Pull request by dmaicher**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #1247

#### Summary

Fixes #1247 by using `getNativeConnection`

### CODE REVIEW

File: lib/Doctrine/Migrations/Tools/TransactionHelper.php [hunk 1]
```diff
@@ -59,13 +60,30 @@ public static function rollbackIfInTransaction(Connection $connection): void
...
+
+    /**
+     * @return Connection|\Doctrine\DBAL\Driver\Connection|object|resource|null
+     */
+    private static function getInnerConnection(Connection $connection)
+    {
+        if (method_exists($connection, 'getNativeConnection')) {
+            try {
+                return $connection->getNativeConnection();
+            } catch (LogicException $e) {
```
Comment (dmaicher) [inline lib/Doctrine/Migrations/Tools/TransactionHelper.php:78]: should we handle this case and ignore it? It might happen if some wrapped connection class does not implement the new method yet...

File: lib/Doctrine/Migrations/Tools/TransactionHelper.php [hunk 2]
```diff
@@ -59,13 +60,30 @@ public static function rollbackIfInTransaction(Connection $connection): void
...
     {
+        $innermostConnection = self::getInnerConnection($connection);
+
+        /* Attempt to commit or rollback while no transaction is running
+           results in an exception since PHP 8 + pdo_mysql combination */
+        return ! $innermostConnection instanceof PDO || $innermostConnection->inTransaction();
+    }
+
+    /**
+     * @return Connection|\Doctrine\DBAL\Driver\Connection|object|resource|null
```
Comment (derrabus) [inline lib/Doctrine/Migrations/Tools/TransactionHelper.php]:
```suggestion
     * @return object|resource|null
```

File: lib/Doctrine/Migrations/Tools/TransactionHelper.php (hunk 1 above)
Comment (derrabus) [reply lib/Doctrine/Migrations/Tools/TransactionHelper.php:78]: This is fine, I guess.

File: phpstan-dbal-3.neon.dist [hunk 3]
```diff
@@ -48,14 +48,9 @@ parameters:
...
-            paths:
-                - lib/Doctrine/Migrations/Generator/DiffGenerator.php
-                - lib/Doctrine/Migrations/Provider/DBALSchemaDiffProvider.php
-
         # Switch to Logging\Connection after dropping compatibility with DBAL 2
         -
             message: '~deprecated.*DebugStack~'
             path: tests/Doctrine/Migrations/Tests/Metadata/Storage/TableMetadataStorageTest.php
+
+        - "~Call to function method_exists\\(\\) with.*\\Connection.*and 'getNativeConnection' will always evaluate to true~"
```
Comment (derrabus) [inline phpstan-dbal-3.neon.dist]: There's a similar rule in lines 38-40 already. Can we merge them?

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @dmaicher!

**Comment by peter17** [comment]
Thanks! Any chance that a 3.4.2 tag could be created to make this fix more available, please? Thanks again!

**Comment by derrabus** [comment]
Done.
