### PR TITLE
Use the standard comment marker in SQL migration files

### LINKED ISSUE #466: --write-sql creates broken sql files on postgresql
It writes comments about the migration into the sql file (see [here](https://github.com/doctrine/migrations/blob/0d0ff5da10c5d30846da32060bd9e357abf70a05/lib/Doctrine/DBAL/Migrations/Migration.php#L95)). Unfortunately it uses the # character which is only a comment in Mysql but not in Postgresql (here it is an [operator](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-SPECIAL-CHARS)).

Because of this we have to transform the file each time before we can actually use it.

I think changing it to `/* */` or `-- ` would be the best way because this is pretty standard among the different vendors. (e.g.: [postgresql](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS), [mysql](http://dev.mysql.com/doc/refman/5.7/en/comments.html), [oracle](https://docs.oracle.com/cd/B14117_01/server.101/b10759/sql_elements006.htm))

### PR DESCRIPTION
**Pull request by aaa2000**
Close #466

### CODE REVIEW

File: lib/Doctrine/DBAL/Migrations/SqlFileWriter.php [hunk 1]
```diff
@@ -107,7 +107,6 @@ private function buildMigrationFilePath()
     {
         $path = $this->destPath;
         if (is_dir($path)) {
-            $path = realpath($path);
```
Comment (aaa2000) [inline lib/Doctrine/DBAL/Migrations/SqlFileWriter.php]: I need to remove the realpath call because https://github.com/mikey179/vfsStream/wiki/Known-Issues

I hope that adding this dependency is not a problem.

**Comment by mikeSimonson** [comment]
@aaa2000 Can you add tests to verify that the removing of the realpath call did not break anything ?

**Comment by aaa2000** [comment]
@mikeSimonson I have keept the realpath call and modified tests by mocking realpath in order to be sure that it did not break anything.

**Comment by mikeSimonson** [comment]
@aaa2000 That works too.
Thanks
